apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: star-test-elemamm-developers-global-io
  namespace: istio-system
spec:
  secretName: star-test-elemamm-developers-global-io
  commonName: "*.test.elemamm.developers.global.io"
  dnsNames:
  - "*.test.elemamm.developers.global.io"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod