apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
resources:
- aadpodidbinding.yaml
bases:
- github.com/kubernetes-sigs/external-dns/kustomize
patchesStrategicMerge:
- external-dns-patch.yaml
patchesJson6902:
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRole
    name: external-dns
  path: rbac-patch.yaml