apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring-elk
resources:
- namespace.yaml
- elastic-secrets.yaml
- filebeat-kubernetes.yaml
- metricbeat-kubernetes.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: DaemonSet
    name: filebeat
  path: filebeat-kubernetes-patch.yaml
- target:
    group: apps
    version: v1
    kind: DaemonSet
    name: metricbeat
  path: metricbeat-kubernetes-patch.yaml
