apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- aadpodidbinding.yaml
- https://github.com/jetstack/cert-manager/releases/download/v1.0.4/cert-manager.yaml
patchesStrategicMerge:
- cert-manager-patch.yaml