apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali-server
  namespace: istio-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kiali-server
      version: '1.35.0'
      sourceRef:
        kind: HelmRepository
        name: kiali-server
        namespace: flux-system
      interval: 1m
      
  test:
    ignoreFailures: true
  
  values:
    istio_namespace: "istio-system"
    external_services:
      custom_dashboards:
        enabled: true
    #deployment:
    #  ingress_enabled: true
      grafana:
        url: http://grafana.monitoring:3000
      prometheus:
        url: http://prometheus-k8s.monitoring:9090/

    