apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: istio-operator
    - name: istio-system
    - name: aad-pod-identity
    - name: external-dns
  path: "./kubernetes-infrastructure/common/cert-manager/"
  prune: true
  validation: client
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager-config
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: cert-manager
  path: "./kubernetes-infrastructure/clusters/aks-dev/private/cert-manager/configuration/"
  validation: client
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system