apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: istio-operator
    - name: istio-system
  path: "./kubernetes-infrastructure/common/external-dns/"
  prune: true
  validation: client
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: external-dns-config
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: external-dns
  path: "./kubernetes-infrastructure/clusters/aks-dev-elemam-02/private/external-dns/configuration/"
  validation: client
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system