apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kured
spec:
  interval: 5m
  chart:
    spec:
      chart: kured
      version: '2.2.0'
      sourceRef:
        kind: HelmRepository
        name: kured
        namespace: flux-system
      interval: 1m
  values:
    configuration:
      rebootDays:
      - "sun"
      startTime: "3:00"
      endTime: "4:00"
    nodeSelector:
      beta.kubernetes.io/os: "linux"