apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-externally-config
  namespace: sonarqube
data:
  SONAR_JDBC_URL: jdbc:postgresql://elemamdevdb.postgres.database.azure.com:5432/sonarqube?user=dbadmin@elemamdevdb&gssEncMode=disable&sslmode=disable
  SONAR_JDBC_USERNAME: dbadmin@elemamdevdb
  SONAR_JDBC_PASSWORD: Sonarqube1
