apiVersion: v1
data:
  DB_PASSWORD: Ym9va3N0YWNrcGFzc3dvcmQ=
kind: Secret
metadata:
  creationTimestamp: "2021-05-31T20:28:44Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:DB_PASSWORD: {}
      f:type: {}
    manager: kubectl-create
    operation: Update
    time: "2021-05-31T20:28:44Z"
  name: bookstack
  namespace: bookstack
  resourceVersion: "2708972"
  selfLink: /api/v1/namespaces/bookstack/secrets/bookstack
  uid: 46820d83-a6d3-418e-b63a-d1782c0446a9
type: Opaque