apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: actions-runner-controller
  namespace: flux-system
spec:
  interval: 1m
  url: https://summerwind.github.io/actions-runner-controller