apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actions-runner-controller
  namespace: actions-runner-system
spec:
  interval: 5m
  chart:
    spec:
      chart: actions-runner-controller
      version: 0.11.0
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
      interval: 1m
      
  test:
    ignoreFailures: true

  values:

    #authSecret:
      #create: true
      #name: controller-manager
      ### GitHub Apps Configuration
      #github_app_id: ""
      #github_app_installation_id: ""
      #github_app_private_key: |
      ### GitHub PAT Configuration
      #github_token: Z2hwXzYwcnNkRmZGY1JOcXlBWWRjcUIxcHpmRUk4cVJRajFzVWppbgo=