apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kubernetes-replicator
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: sealed-secrets
  path: "./kubernetes-infrastructure/common/kubernetes-replicator/"
  prune: true
  validation: client
  sourceRef:
    kind: GitRepository
    name: flux-system