apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 5m
  path: "./kubernetes-infrastructure/common/sealed-secrets/"
  prune: true
  validation: client
  sourceRef:
    kind: GitRepository
    name: flux-system