apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-claim
  namespace: sonarqube
  labels:
    app: sonarqube
spec:
  storageClassName: managed-premium-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

