apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluentd
  namespace: monitoring-efk
spec:
  interval: 5m
  chart:
    spec:
      chart: fluentd
      version: '0.2.6'
      sourceRef:
        kind: HelmRepository
        name: fluentd
        namespace: flux-system
      interval: 1m
      
  test:
    ignoreFailures: true
  
  values:
 