apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
secretGenerator:
  - name: azure-config-file
    behavior: create
    files:
      - azure.json
    type: "kubernetes.io/generic"
generatorOptions:
  disableNameSuffixHash: true
resources:
- namespace.yaml