apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: github-actions-runner-operator
  namespace: github-actions-runner
spec:
  interval: 5m
  chart:
    spec:
      chart: github-actions-runner-operator
      version: '2.6.1'
      sourceRef:
        kind: HelmRepository
        name: github-actions-runner-operator
        namespace: flux-system
      interval: 1m
  values:
    envFrom:
    - secretRef:
        name: github-runner-app
    githubapp:
      enabled: true
      existingSecret: "github-runner-app"