apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: github-actions-runner-operator
  namespace: flux-system
spec:
  interval: 1m
  url: https://evryfs.github.io/helm-charts
