apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubernetes-replicator
  namespace: kubernetes-replicator
spec:
  interval: 5m
  chart:
    spec:
      chart: kubernetes-replicator
      version: '2.5.0'
      sourceRef:
        kind: HelmRepository
        name: kubernetes-replicator
        namespace: flux-system
      interval: 1m